
# basic options
title: Franz on GH 
author: GitHub User
email: fnz.amigoni@gmail.com 
description: A wonderful site
twitter_username: franzamigoni
github_username:  franzamigoni

# Build settings
markdown: kramdown
theme: minima

